import Header from '../components/layout/Header'
import '../globals.css'
import { Inter } from 'next/font/google'
import Content from '../components/layout/Content'
import Footer from '../components/layout/Footer'
import { authOptions } from '../api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import getCurrentUser from '../services/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  // if (!session) redirect('/session/login')
  const currentUser = await getCurrentUser()

  return (
    <html lang='en' data-theme='dark'>
      <body className={`${inter.className}`}>
        <Header currentUser={currentUser} />
        <Content>{children}</Content>
        <Footer />
      </body>
    </html>
  )
}
